trigger:
  branches:
    include:
      - master  # or 'main' — update if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: "-Xmx2g"

steps:
  - task: Bash@3
    displayName: 'Run Gatling Load Test via Maven Wrapper'
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./mvnw
        ./mvnw clean test-compile gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

  - task: Bash@3
    displayName: 'Zip Gatling Report with Timestamp'
    inputs:
      targetType: 'inline'
      script: |
        REPORT_DIR=$(find reports -maxdepth 1 -type d -name 'authdummyjson-*' | sort | tail -n 1)
        if [ -z "$REPORT_DIR" ]; then
          echo "❌ No Gatling report directory found"
          exit 1
        fi
        echo "✅ Found report: $REPORT_DIR"
        TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
        ZIP_NAME="gatling-report-${TIMESTAMP}.zip"
        echo "##vso[task.setvariable variable=ZIP_NAME]$ZIP_NAME"
        cd "$REPORT_DIR"
        zip -r "../../$ZIP_NAME" .

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Timestamped Gatling Report ZIP'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/$(ZIP_NAME)'
      artifact: '$(ZIP_NAME)'
      publishLocation: 'pipeline'