trigger:
  branches:
    include:
      - master  # or main, depending on your repo

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: "-Xmx2g"

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test-compile gatling:test'
      options: '-Dgatling.simulationClass=gatling_fundamentals.Basics'
    displayName: 'Run Gatling Load Test'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'target/gatling'
      artifact: 'gatling-report'
      publishLocation: 'pipeline'
    displayName: 'Publish Gatling Report'