name: Gatling Load Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  gatling:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Gatling Simulation
        run: |
          chmod +x ./mvnw
          ./mvnw gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

      - name: Copy Latest Gatling Report Preserving Folder
        run: |
          set -e
          mkdir -p committed-reports
          REPORT_DIR=$(find reports -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
          if [ -z "$REPORT_DIR" ]; then
            echo "❌ No report found in /reports"
            exit 1
          fi
          echo "✅ Found report: $REPORT_DIR"
          BASENAME=$(basename "$REPORT_DIR")
          cp -r "$REPORT_DIR" "committed-reports/$BASENAME"

      - name: Commit Full Report Folder to Main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add committed-reports/** -f
          git commit -m "📊 Add Gatling report: $BASENAME [CI]" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GATLING_API_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main