name: Gatling Load Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gatling:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Gatling Simulation
        run: |
          chmod +x ./mvnw
          ./mvnw gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

      - name: Copy Latest Gatling Report
        run: |
          mkdir -p report-to-push
          LATEST=$(ls -td target/gatling/*/ | head -n1)
          echo "Latest report: $LATEST"
          cp -r "$LATEST"/* report-to-push/

      - name: Push Report to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔁 Auto-publish Gatling report"
          branch: main
          file_pattern: report-to-push/**
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com