name: Gatling Load Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gatling:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Gatling Simulation
        run: |
          chmod +x ./mvnw
          ./mvnw gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

      - name: Copy Latest Gatling Report
        run: |
          set -e
          REPORT_DIR=$(find reports -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
          if [ -z "$REPORT_DIR" ]; then
            echo "❌ No Gatling report directory found in /reports"
            exit 1
          fi
          echo "✅ Found report at $REPORT_DIR"
          mkdir -p public
          cp -r "$REPORT_DIR"/* public/

      - name: Publish to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.GATLING_API_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
          cd gh-pages
          rm -rf ./*
          cp -r ../public/* .
          touch .nojekyll
          git add .
          git commit -m "🚀 Publish Gatling report to GitHub Pages [CI]" || echo "Nothing to commit"
          git push origin gh-pages