name: Gatling Load Test

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

jobs:
  gatling:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Gatling Simulation
        run: |
          chmod +x ./mvnw
          ./mvnw clean test-compile gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

      - name: Debug - List contents of reports/
        run: |
          echo "Listing contents of ./reports"
          ls -R reports || echo "❌ reports directory does not exist"

      - name: Compress Gatling Report with Timestamp
        run: |
          REPORT_DIR=$(find reports -maxdepth 1 -type d -name 'authdummyjson-*' | sort | tail -n 1)
          if [ -z "$REPORT_DIR" ]; then
            echo "❌ No Gatling report folder found in ./reports"
            exit 1
          fi
          echo "✅ Found report folder: $REPORT_DIR"
          TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
          ZIP_NAME="gatling-report-${TIMESTAMP}.zip"
          zip -r "$ZIP_NAME" "$REPORT_DIR"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Confirm Zip File Exists
        run: |
          if [ ! -f "${{ env.ZIP_NAME }}" ]; then
            echo "❌ Zip file was not created"
            exit 1
          fi
          echo "✅ ${{ env.ZIP_NAME }} created"
          ls -lh "${{ env.ZIP_NAME }}"

      - name: Upload Gatling Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}
