name: Gatling Load Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gatling:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Gatling Simulation
        run: |
          chmod +x ./mvnw
          ./mvnw gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

      - name: Debug - List Gatling Output
        run: |
          echo "Showing files inside target/gatling"
          ls -R target/gatling || echo "No files found"

      - name: Compress Gatling Report
        run: |
          REPORT_DIR=$(find target/gatling -maxdepth 1 -type d -name '*AuthDummyJSON*' | head -n 1)
          echo "Zipping $REPORT_DIR"
          zip -r gatling-report.zip "$REPORT_DIR"

      - name: Upload Gatling Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gatling-report
          path: gatling-report.zip
