name: Gatling Load Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gatling:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Gatling Simulation
        run: |
          chmod +x ./mvnw
          ./mvnw gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

      - name: Debug - List Reports Output
        run: |
          echo "Contents of /reports:"
          ls -R reports || echo "❌ No 'reports/' directory found."

      - name: Copy Latest Gatling Report from /reports
        run: |
          set -e
          REPORT_DIR=$(find reports -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
          if [ -z "$REPORT_DIR" ]; then
            echo "❌ No Gatling report directory found in /reports"
            exit 1
          fi
          echo "✅ Found report at $REPORT_DIR"
          mkdir -p report-to-push
          cp -r "$REPORT_DIR"/* report-to-push/

      - name: Commit Gatling Report to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Auto-publish Gatling report from /reports"
          branch: main
          file_pattern: report-to-push/**
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
