name: Gatling Load Test

on:
  push:
    branches:
      - main  # Change to 'master' if that’s your default branch

jobs:
  gatling:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gatling Load Test
        run: |
          ./mvnw gatling:test -Dgatling.simulationClass=simulations.AuthDummyJSON

      - name: Compress Gatling Report
        if: always()
        run: zip -r gatling-report.zip target/gatling

      - name: Upload Gatling Report Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: gatling-report
          path: gatling-report.zip